services:

  # React ya compilado para producción.
  # La imagen ya fue construida por GitHub Actions.
  client:
    image: gabomur/multi-client:latest
    mem_limit: 128m

  # API Express.
  # Lo llamamos "api" porque nuestro nginx/default.conf
  # resuelve al backend usando el nombre api.
  api:
    image: gabomur/multi-server:latest
    mem_limit: 128m
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      PGUSER: ${PGUSER}
      PGHOST: ${PGHOST}
      PGDATABASE: ${PGDATABASE}
      PGPASSWORD: ${PGPASSWORD}
      PGPORT: ${PGPORT}

  # Worker que calcula Fibonacci.
  # Solo necesita Redis.
  worker:
    image: gabomur/multi-worker:latest
    mem_limit: 128m
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

  # Reverse proxy principal.
  nginx:
    image: gabomur/multi-nginx:latest
    mem_limit: 128m
    ports:
      - "80:80"
    depends_on:
      - client
      - api
